// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/approve": {
            "post": {
                "description": "Phê duyệt số lượng token cho địa chỉ chi tiêu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Phê duyệt token",
                "parameters": [
                    {
                        "description": "Thông tin phê duyệt token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ApproveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/balances/{address}": {
            "get": {
                "description": "Lấy số dư token của một địa chỉ Ethereum",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Lấy số dư token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Địa chỉ Ethereum",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.BalanceResponse"
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/burn": {
            "post": {
                "description": "Đốt một số lượng token từ địa chỉ chỉ định",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Đốt token",
                "parameters": [
                    {
                        "description": "Thông tin đốt token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.BurnRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/add-co-owner": {
            "post": {
                "description": "Tạo sự kiện để thêm một đồng sở hữu mới",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Tạo sự kiện thêm đồng sở hữu",
                "parameters": [
                    {
                        "description": "Thông tin yêu cầu thêm đồng sở hữu",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateAddCoOwnerEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateAddCoOwnerEventResponse"
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Lỗi xử lý sự kiện",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/burn": {
            "post": {
                "description": "Tạo sự kiện để đốt token với số lượng chỉ định",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Tạo sự kiện đốt token",
                "parameters": [
                    {
                        "description": "Thông tin yêu cầu đốt token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateBurnTokenEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateBurnTokenEventResponse"
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Lỗi xử lý sự kiện",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/mint": {
            "post": {
                "description": "Tạo một sự kiện mint token với số lượng chỉ định",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Tạo sự kiện mint token",
                "parameters": [
                    {
                        "description": "Thông tin yêu cầu mint",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateMintEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateMintEventResponse"
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Lỗi xử lý sự kiện",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/pause": {
            "post": {
                "description": "Tạo sự kiện để tạm dừng hoạt động hợp đồng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Tạo sự kiện tạm dừng",
                "parameters": [
                    {
                        "description": "Thông tin yêu cầu tạm dừng",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreatePauseEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.CreatePauseEventResponse"
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Lỗi xử lý sự kiện",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/sign": {
            "post": {
                "description": "Ký hoặc từ chối một sự kiện hiện có",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Ký sự kiện",
                "parameters": [
                    {
                        "description": "Thông tin yêu cầu ký",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.SignEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.SignEventResponse"
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Lỗi xử lý sự kiện",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/unpause": {
            "post": {
                "description": "Tạo sự kiện để bỏ tạm dừng hoạt động hợp đồng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Tạo sự kiện bỏ tạm dừng",
                "parameters": [
                    {
                        "description": "Thông tin yêu cầu bỏ tạm dừng",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateUnpauseEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateUnpauseEventResponse"
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Lỗi xử lý sự kiện",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transfer": {
            "post": {
                "description": "Thực hiện chuyển token từ địa chỉ này sang địa chỉ khác",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Chuyển token",
                "parameters": [
                    {
                        "description": "Thông tin chuyển token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Xác thực người dùng với email và mật khẩu để lấy JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Đăng nhập người dùng",
                "parameters": [
                    {
                        "description": "Thông tin đăng nhập",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Xác thực không thành công",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Tạo tài khoản mới với email, mật khẩu và tên",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Đăng ký người dùng mới",
                "parameters": [
                    {
                        "description": "Thông tin đăng ký",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.ApproveRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "jwt": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "spender": {
                    "type": "string"
                }
            }
        },
        "controllers.BalanceResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "string"
                }
            }
        },
        "controllers.BurnRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "string"
                },
                "jwt": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateAddCoOwnerEventRequest": {
            "type": "object",
            "properties": {
                "jwt": {
                    "type": "string"
                },
                "newCoOwner": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateAddCoOwnerEventResponse": {
            "type": "object",
            "properties": {
                "eventId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transactionHash": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateBurnTokenEventRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "jwt": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateBurnTokenEventResponse": {
            "type": "object",
            "properties": {
                "eventId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transactionHash": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateMintEventRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "jwt": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateMintEventResponse": {
            "type": "object",
            "properties": {
                "eventId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transactionHash": {
                    "type": "string"
                }
            }
        },
        "controllers.CreatePauseEventRequest": {
            "type": "object",
            "properties": {
                "jwt": {
                    "type": "string"
                }
            }
        },
        "controllers.CreatePauseEventResponse": {
            "type": "object",
            "properties": {
                "eventId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transactionHash": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateUnpauseEventRequest": {
            "type": "object",
            "properties": {
                "jwt": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateUnpauseEventResponse": {
            "type": "object",
            "properties": {
                "eventId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transactionHash": {
                    "type": "string"
                }
            }
        },
        "controllers.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "controllers.LoginUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controllers.RegisterUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controllers.SignEventRequest": {
            "type": "object",
            "properties": {
                "approve": {
                    "type": "boolean"
                },
                "eventId": {
                    "type": "string"
                },
                "jwt": {
                    "type": "string"
                }
            }
        },
        "controllers.SignEventResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "transactionHash": {
                    "type": "string"
                }
            }
        },
        "controllers.TransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "jwt": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
